#ifndef _VIEWS_CONFIGURATION_H
#define _VIEWS_CONFIGURATION_H

#define STATUS_BAR_HEIGHT_PERCENTAGE 5
#define CONSOLE_HEIGHT_PERCENTAGE STATYS_BAR_HEIGHT_PERCENTAGE
#define BG_COLOR GREY

#endif /* _VIEWS_CONFIGURATION_H */